/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';


export const REDUX_ACTION_TYPE = {
  ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
  DELETE_ITEM_FROM_CART: ' DELETE_ITEM_FROM_CART',
  UPDATE_PRODUCT_QUANTITY: 'UPDATE_PRODUCT_QUANTITY',
  OPEN_LOGIN_DIALOG: 'OPEN_LOGIN_DIALOG',
  SET_USER: 'SET_USER',
  RESET_CART: 'RESET_CART',
};
